### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by hannesa2** [ViktorYellows/testPanoramaGl#1]
Ahh, the necessary action is switching the panorama ! This was not clear to me.

My first manual test results in a stable memory consumption without a out of memory error
![image](https://user-images.githubusercontent.com/3314607/129666372-3ca0da69-2e3d-42a9-a268-c1b87151861d.png)

I will automate it....

**Comment by hannesa2** [comment]
Test in main repo 
https://github.com/hannesa2/panoramagl/pull/92

**Comment by ViktorYellows** [comment]
I add high resoultion 360 images to repo, and migrate from .aar

I test on real device Xiaomi Redmi Note 8 (Android 9)

First test results when app is launched
![Снимок экрана 2021-08-17 в 09 41 41](https://user-images.githubusercontent.com/66410646/129676864-5a911cf5-34ed-4891-8294-6cd4fdcfdf9c.png)

Second test results when i switch panoramas 3 times, memory increased and app freezes
![Снимок экрана 2021-08-17 в 09 43 03](https://user-images.githubusercontent.com/66410646/129676957-961c91d5-7dc6-47a7-957e-0c31a63e1d12.png)

1. Do You know why app is freezing if Your phone's (Pixel_API_30) RAM is stable while first manual test?
2. Does library provides gyroscope rotation of panoramas?

Also, please try to test on real device, not emulator

**Comment by hannesa2** [comment]
PR for testing https://github.com/ViktorYellows/testPanoramaGl/pull/3

**Comment by hannesa2** [comment]
> * Do You know why app is freezing if Your phone's (Pixel_API_30) RAM is stable while first manual test?

No clue why 

> * Does library provides gyroscope rotation of panoramas?

Here you have it https://github.com/hannesa2/panoramagl/blob/56138455232ec437af08d7a137846574dcb5208f/library/src/main/java/com/panoramagl/PLManager.kt#L907-L917
