### ISSUE TITLE
Usage of panoramaGl as aar

### ISSUE THREAD

**Issue by hannesa2** [ViktorYellows/testPanoramaGl#2]
Usage as copied aar is not necessary, I fixed jitpack.io https://jitpack.io/#hannesa2/panoramagl
and now you can use it from repository as well again

```
allprojects {
  repositories {
   ...
   maven { url 'https://jitpack.io' }
  }
}
```

	dependencies {
	        implementation 'com.github.hannesa2:panoramagl:1.7.1'
	}

**Comment by ViktorYellows** [comment]
i've changed this, thanks
